name: nativechat
description: "Advanced AI-powered mobile assistant with multi-provider support, voice interaction, and comprehensive device integration capabilities."

# Prevent accidental publishing to pub.dev
publish_to: "none"

# Version: semantic versioning with build number
# In Android: build-name = versionName, build-number = versionCode
# In iOS: build-name = CFBundleShortVersionString, build-number = CFBundleVersion
# In Windows: build-name = major.minor.patch, build-number = build suffix
version: 1.8.1+18

environment:
    sdk: ^3.6.2

dependencies:
    flutter:
        sdk: flutter

    # UI & Icons
    cupertino_icons: ^1.0.8
    ionicons: ^0.2.2
    mobkit_dashed_border: ^0.0.7
    loading_animation_widget: ^1.3.0
    animated_text_kit: ^4.2.3
    theme_provider: ^0.6.0
    easy_image_viewer: ^1.5.1
    cherry_toast: ^1.12.0
    selectable: ^0.5.0
    flutter_staggered_animations: ^1.1.1
    lottie: ^3.3.0
    shimmer: ^3.0.0

    # State Management & Architecture
    provider: ^6.1.2
    flutter_riverpod: ^2.5.1

    # AI & Language Models
    google_generative_ai: ^0.4.6
    dio: ^5.8.0+1
    http: ^1.2.2

    # Device Integration & Permissions
    permission_handler: ^12.0.1
    flutter_sms_inbox: ^1.0.4
    battery_plus: ^6.2.1
    call_log_new: ^1.0.5
    installed_apps: ^1.5.2
    system_info2: ^4.0.0
    device_info_plus: ^11.3.0
    network_info_plus: ^6.1.3
    geolocator: ^13.0.2

    # Voice & Audio
    speech_to_text: ^7.0.0
    flutter_tts: ^4.2.2

    # File Handling & Media
    file_picker: ^9.0.2
    image_picker: ^1.1.2
    url_launcher: ^6.3.1
    share_plus: ^10.1.2
    path_provider: ^2.1.5
    cached_network_image: ^3.4.1
    photo_view: ^0.15.0

    # Data & Storage
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    uuid: ^4.5.1
    intl: ^0.20.2

    # Content & Sharing
    flutter_sharing_intent: ^1.1.1
    gpt_markdown: ^1.0.9
    flutter_highlight: ^0.7.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: "^0.14.3"
    hive_generator: ^2.0.1
    build_runner: ^2.4.15
    flutter_lints: ^5.0.0

# App Icon Configuration
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/logo/logo.png"
    min_sdk_android: 21
    web:
        generate: true
        image_path: "assets/logo/logo.png"
        background_color: "#1a1a1a"
        theme_color: "#4285f4"
    windows:
        generate: true
        image_path: "assets/logo/logo.png"
        icon_size: 48
    macos:
        generate: true
        image_path: "assets/logo/logo.png"

# Flutter Configuration
flutter:
    uses-material-design: true
    
    # Assets
    assets:
        - assets/logo/logo.png
        - assets/logo/logoBorder.png
        - assets/banners/
        - assets/promos/

    # Custom fonts can be added here if needed
    # fonts:
    #   - family: CustomFont
    #     fonts:
    #       - asset: fonts/CustomFont-Regular.ttf
    #       - asset: fonts/CustomFont-Bold.ttf
    #         weight: 700