name: Flutter APK Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        cache: true
        
    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor --android-licenses || true
        flutter doctor
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Generate code files (if needed)
      run: flutter packages pub run build_runner build --delete-conflicting-outputs || true
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      
    - name: Build APK (Debug)
      run: flutter build apk --debug
      
    - name: Build APK (Release)
      run: flutter build apk --release
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 30
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 90
        
    - name: Build App Bundle (Release)
      run: flutter build appbundle --release
      
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 90

  build-info:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    
    steps:
    - name: Build Summary
      run: |
        echo "## 🎉 Flutter APK Build Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📱 Available Downloads:" >> $GITHUB_STEP_SUMMARY
        echo "- **Debug APK**: Ready for testing" >> $GITHUB_STEP_SUMMARY
        echo "- **Release APK**: Production ready" >> $GITHUB_STEP_SUMMARY
        echo "- **App Bundle**: Play Store ready" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📥 How to Download:" >> $GITHUB_STEP_SUMMARY
        echo "1. Go to **Actions** tab" >> $GITHUB_STEP_SUMMARY
        echo "2. Click on this workflow run" >> $GITHUB_STEP_SUMMARY
        echo "3. Scroll down to **Artifacts** section" >> $GITHUB_STEP_SUMMARY
        echo "4. Download your preferred APK" >> $GITHUB_STEP_SUMMARY